# Generated by Django 5.2.17 on 2026-08-29 11:16

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, default=orders.models._order_number, max_length=50, unique=True)),
                ('tracking_number', models.CharField(db_index=True, default=orders.models._tracking_number, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(max_length=30)),
                ('delivery_address', models.CharField(max_length=500)),
                ('delivery_lat', models.FloatField(blank=True, null=True)),
                ('delivery_lng', models.FloatField(blank=True, null=True)),
                ('origin_city', models.CharField(blank=True, default='', max_length=120)),
                ('destination_city', models.CharField(blank=True, default='', max_length=120)),
                ('commodity', models.CharField(default='General Cargo', max_length=255)),
                ('weight_kg', models.FloatField(default=0.0)),
                ('declared_value', models.FloatField(default=0.0)),
                ('is_cod', models.BooleanField(default=False)),
                ('cod_amount', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('order_received', 'Order Received'), ('booking_planned', 'Booking Planned'), ('pickup_completed', 'Pickup Completed'), ('label_verified', 'Label Verified'), ('manifest_created', 'Manifest Created'), ('at_origin_hub', 'At Origin Hub'), ('sorted_at_origin', 'Sorted at Origin'), ('dispatched_linehaul', 'Dispatched (Linehaul)'), ('at_destination_hub', 'At Destination Hub'), ('route_planned', 'Route Planned'), ('out_for_delivery', 'Out for Delivery'), ('delivery_attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('closed', 'Closed / Billed'), ('delivery_failed', 'Delivery Failed'), ('reattempt_scheduled', 'Reattempt Scheduled'), ('rto_initiated', 'RTO Initiated'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], db_index=True, default='order_received', max_length=25)),
                ('pickup_date', models.CharField(blank=True, max_length=20, null=True)),
                ('pickup_slot', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_attempt_count', models.IntegerField(default=0)),
                ('freight_charge', models.FloatField(default=0.0)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_amount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='fleet.driver')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_received', 'Order Received'), ('booking_planned', 'Booking Planned'), ('pickup_completed', 'Pickup Completed'), ('label_verified', 'Label Verified'), ('manifest_created', 'Manifest Created'), ('at_origin_hub', 'At Origin Hub'), ('sorted_at_origin', 'Sorted at Origin'), ('dispatched_linehaul', 'Dispatched (Linehaul)'), ('at_destination_hub', 'At Destination Hub'), ('route_planned', 'Route Planned'), ('out_for_delivery', 'Out for Delivery'), ('delivery_attempted', 'Delivery Attempted'), ('delivered', 'Delivered'), ('closed', 'Closed / Billed'), ('delivery_failed', 'Delivery Failed'), ('reattempt_scheduled', 'Reattempt Scheduled'), ('rto_initiated', 'RTO Initiated'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], max_length=25)),
                ('document_name', models.CharField(max_length=150)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
